### ISSUE TITLE
Volumes are created but not mounted

### ISSUE THREAD

**Issue by robojones** [kadalu/kadalu#303]
When I create multiple volume claims in a short timeframe, they are created but not mounted in the containers. I am pretty sure that this is an issue with kadalu. Any help is welcome!

Kadalu is configured as default storage class in my cluster. With small deployments using few volumes this works fine.
Now I am trying to install the [Harbor helmchart](https://github.com/goharbor/harbor-helm) which creates more than 10 pods with volume claims and every time some of them are stuck in the `ContainerCreating` phase. The volume claims are all created and bound, but attaching them to the containers fails.

To verify that this is not an issue with the Harbor helmchart, I created a simple deployment with 9 nginx containers and 9 PVCs.

**Minimal example:** [deployment.yaml](https://gist.github.com/robojones/df924fe209f106c1bc26b066db1fa9dc#file-deployment-yaml)

The pods which stuck in the `ContainerCreating` state always log the events:
- `FailedScheduling` with message `error while running "VolumeBinding" filter plugin for pod "...": pod has unbound immediate PersistentVolumeClaims`
- Later followed by:
`FailedMount` with the message `Unable to attach or mount volumes: unmounted volumes=[...]: timed out waiting for the condition`

**Full event log from kubectl describe:** [events.txt](https://gist.github.com/robojones/df924fe209f106c1bc26b066db1fa9dc#file-events-txt)

**Comment by amarts** [comment]
Thanks for the report. Can you check the logs of `kadalu-csi-nodeplugin` pods, and see if you find any issues there?

**Comment by robojones** [comment]
@amarts the kadalu-csi-nodeplugin pods have been running for the past five days. The logs look fine to me but I have uploaded them [here](https://gist.github.com/robojones/2a9b1d4c5bd541abe365ace98adb090d), so you can take a look.

**Comment by amarts** [comment]
Interesting, the volume Attach is an operation to be handled by nodeplugin, so not all PVC requests came to the nodeplugin (or this particular nodeplugin. Can you check if there are kadalu-nodeplugin running in all nodes which needs the mount? there should be just 1 kadalu csi provisioner , but per node 1 nodeplugins. (if not, then there is an issue), and the mount issue may be from only few nodeplugins.

**Comment by robojones** [comment]
I checked and `kadalu-nodeplugin` is running on all of my nodes. Here is a screenshot of my Rancher dashboard.
![image](https://user-images.githubusercontent.com/21033651/93747768-76fce300-fbf7-11ea-980e-e269410db528.png)

**Comment by robojones** [comment]
I have toyed around with my [example deployment](https://gist.github.com/robojones/df924fe209f106c1bc26b066db1fa9dc#file-deployment-yaml). 

When I mount only specific volumes then some volumes work, while others don't. For example, when I run only one pod with a single container and mount the PVC called "volume-claim-3" the container always hangs because the volume cannot be mounted. When I use "volume-claim-2" the pod starts without problems. Kubernetes displays all the PVCs as "Bound". The node on which the pod is scheduled does not seem to matter. Maybe there is something going wrong when the volumes are created?

**Comment by amarts** [comment]
@robojones any hints in `kadalu-csi-provisioner` logs ?

**Comment by robojones** [comment]
@amarts created the whole cluster from scratch just to make sure this is not caused by any misconfiguration in the cluster. The issue remains.

Here are my [kadalu-csi-provisioner logs](https://gist.github.com/robojones/3416fb53369a534d88b29145b7c3d8e7).

**Comment by robojones** [comment]
I think the errors in controller.go are interesting. They come up quite a bit in the [cli-provisioner log](https://gist.github.com/robojones/3416fb53369a534d88b29145b7c3d8e7#file-csi-provisioner-L49).

`[controller.go:1443] couldn't create key for object pvc-...: object has no meta: object does not implement the Object interfaces`

**Comment by amarts** [comment]
Yes, suspect the same! Let me try to figure out why that comes up!

**Comment by robojones** [comment]
The Kubernetes permission error [here](https://gist.github.com/robojones/3416fb53369a534d88b29145b7c3d8e7#file-csi-attacher-L22) could be important too. Maybe a misconfigured ClusterRole?

`Error saving VolumeAttachment csi-80c66f7c847c949e41e3bffa0bbeefbe3d742a8a8e3d26dabb406ac4d19a41fa as attached: volumeattachments.storage.k8s.io "csi-80c66f7c847c949e41e3bffa0bbeefbe3d742a8a8e3d26dabb406ac4d19a41fa" is forbidden: User "system:serviceaccount:kadalu:kadalu-csi-provisioner" cannot patch resource "volumeattachments/status" in API group "storage.k8s.io" at the cluster scope`

**Comment by amarts** [comment]
> User "system:serviceaccount:kadalu:kadalu-csi-provisioner" cannot patch resource "volumeattachments/status" in API group "storage.k8s.io" at the cluster scope

Which version are you using?  the `devel` tag should fix it, as we fixed the same in one of the latest patch (#299 )

**Comment by robojones** [comment]
According to `pip freeze` I have version 0.7.0

**Comment by robojones** [comment]
I installed kadalu into the cluster today using `kubectl kadalu install`.

**Comment by amarts** [comment]
Can you try 

`kubectl create -f https://raw.githubusercontent.com/kadalu/kadalu/devel/manifests/kadalu-operator-devel.yaml`

**Comment by robojones** [comment]
Sure :smiley: 
I ran the following command.
`kubectl -n kadalu apply -f https://raw.githubusercontent.com/kadalu/kadalu/devel/manifests/kadalu-operator-devel.yaml`

The output is:
```
namespace/kadalu unchanged
serviceaccount/kadalu-operator unchanged
serviceaccount/kadalu-csi-nodeplugin unchanged
serviceaccount/kadalu-csi-provisioner unchanged
serviceaccount/kadalu-server-sa unchanged
customresourcedefinition.apiextensions.k8s.io/kadalustorages.kadalu-operator.storage unchanged
clusterrole.rbac.authorization.k8s.io/kadalu-operator configured
clusterrolebinding.rbac.authorization.k8s.io/kadalu-operator unchanged
deployment.apps/operator configured
```

I am still seeing the permission error in the `csi-attacher` log. The test deployment still fails.

**Comment by amarts** [comment]
may be because its not restarting any `csi-`* pods. Please kill all the kadalu `csi-nodeplugin` and `csi-provisioner` pods, and let the new operator start them.

**Comment by robojones** [comment]
I deleted the pods and Kubernetes scheduled them again. It did not change anything.

**Comment by robojones** [comment]
Is there a way to completely remove kadalu and then reinstall it using the operator with devel tag?

**Comment by robojones** [comment]
I am pretty sure that I know why the operator is unable to upgrade the other components. The operator uses `kubectl create` to create the Kubernetes objects. Maybe this should be changed to `kubectl apply` wherever possible so the objects can be updated by a newer operator.

**Comment by amarts** [comment]
> Is there a way to completely remove kadalu and then reinstall it using the operator with devel tag?

https://github.com/kadalu/kadalu/blob/master/extras/scripts/cleanup

**Comment by aravindavk** [comment]
Open issue related to Storage pods upgrade https://github.com/kadalu/kadalu/issues/242

**Comment by robojones** [comment]
I have removed kadalu with the cleanup script and reinstalled it using the [devel config](https://github.com/kadalu/kadalu/blob/devel/manifests/kadalu-operator-devel.yaml). My pod is now starting and all volumes are attached successfully. Maybe it's time for a new release :tada: 

This error still remains but it does not seem to affect my deployment:

> I think the errors in controller.go are interesting. They come up quite a bit in the [cli-provisioner log](https://gist.github.com/robojones/3416fb53369a534d88b29145b7c3d8e7#file-csi-provisioner-L49).
> 
> `[controller.go:1443] couldn't create key for object pvc-...: object has no meta: object does not implement the Object interfaces`

**Comment by amarts** [comment]
> Maybe it's time for a new release :tada: 

@aravindavk what do you think? lets take #305 and make a release?

**Comment by aravindavk** [comment]
> @aravindavk what do you think? lets take #305 and make a release?

Server pods will not be upgraded automatically if Operator is upgraded. #242 needs to be fixed. Agree on the release part. Good to make a release.

**Comment by amarts** [comment]
Can we close this issue as the new release is made, and that should help in resolving ?

For the other logs, and issues, we can have separate issues to track them.

**Comment by robojones** [comment]
I successfully started the Harbor helmchart and all volumes are mounted without problems. The issue seems to be fixed in the latest release.

Thanks a lot for the help @amarts :+1:
